Allow specifying additional system packages to be installed
caktus/tequila-django pull request #48
Opened 2019-09-18 13:56 UTC by cchurch

Add ``app_packages`` variable for specifying additional system packages to be installed.

2019-09-23 13:30 UTC, copelco requested changes

2019-09-23 13:30 UTC, copelco commented on tasks/web.yml
> -- name: copy shell script wrapper for manage.py
Why is this removed?

2019-09-24 13:54 UTC, cchurch commented on tasks/web.yml
> -- name: copy shell script wrapper for manage.py
That same task already exists in `main.yml`.

2019-09-24 14:01 UTC, copelco approved these changes

2019-09-24 14:49 UTC, merged